import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import type { GenerateResult } from '@/app/api/generate/route';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export async function copyToClipboard(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text);
    return;
  } catch {
    // Fallback for browsers where clipboard API is unavailable or denied
  }
  const textarea = document.createElement('textarea');
  textarea.value = text;
  textarea.style.cssText = 'position:fixed;top:0;left:0;opacity:0;pointer-events:none';
  document.body.appendChild(textarea);
  textarea.focus();
  textarea.select();
  try {
    document.execCommand('copy');
  } finally {
    document.body.removeChild(textarea);
  }
}

export function buildDownloadContent(result: GenerateResult): string {
  const lang = result.language ?? '';
  const isLineComment = lang === 'typescript' || lang === 'groovy';
  const c = isLineComment ? '//' : '#';
  if (lang === 'json') return result.script ?? '';

  const sep = `${c} ${'='.repeat(62)}`;
  const lines: string[] = [
    sep,
    `${c} ${result.title ?? 'Generated Script'}`,
    `${c} Generated by TaskPilot — taskpilot-umber.vercel.app`,
    sep,
  ];

  if (result.explanation) {
    lines.push(`${c}`);
    lines.push(`${c} DESCRIPTION:`);
    const words = result.explanation.split(' ');
    let currentLine = `${c}  `;
    for (const word of words) {
      if (currentLine.length + word.length + 1 > 78) {
        lines.push(currentLine.trimEnd());
        currentLine = `${c}  ${word} `;
      } else {
        currentLine += `${word} `;
      }
    }
    if (currentLine.trim() !== c) lines.push(currentLine.trimEnd());
  }

  if (result.configNotes && result.configNotes.length > 0) {
    lines.push(`${c}`);
    lines.push(`${c} BEFORE YOU RUN:`);
    for (const note of result.configNotes) {
      lines.push(`${c}  → ${note}`);
    }
  }

  lines.push(sep);
  lines.push('');
  lines.push(result.script ?? '');
  return lines.join('\n');
}

const LANG_RUN_INSTRUCTIONS: Record<string, string[]> = {
  powershell: [
    'Open PowerShell as Administrator.',
    'If needed, allow execution: `Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`',
    `Run: \`.\\${'{filename}'}\``,
  ],
  bash: [
    'Open a terminal.',
    'Make executable: `chmod +x {filename}`',
    'Run: `./{filename}`',
  ],
  python: [
    'Ensure Python 3.8+ is installed: `python --version`',
    'Install dependencies if listed at the top of the script.',
    'Run: `python {filename}`',
  ],
  terraform: [
    'Ensure Terraform is installed: `terraform --version`',
    'Initialise: `terraform init`',
    'Preview changes: `terraform plan`',
    'Apply: `terraform apply`',
  ],
  yaml: [
    'Review the YAML and adjust variables to match your environment.',
    'Apply with your tool (e.g. `kubectl apply -f {filename}` or your CI/CD pipeline).',
  ],
  dockerfile: [
    'Build the image: `docker build -t my-image .`',
    'Run a container: `docker run my-image`',
  ],
};

export function buildScriptGuide(result: GenerateResult): string {
  const title = result.title ?? 'Generated Script';
  const lang = result.language ?? '';
  const filename = result.filename ?? 'script';
  const lines: string[] = [
    `# ${title}`,
    ``,
    `> Generated by TaskPilot — https://taskpilot-umber.vercel.app`,
    ``,
  ];

  if (result.explanation) {
    lines.push(`## Overview`, ``, result.explanation, ``);
  }

  lines.push(`**File:** \`${filename}\``, ``);

  if (result.configNotes && result.configNotes.length > 0) {
    lines.push(`## Before You Run`, ``, `Complete these steps before executing the script:`, ``);
    for (const note of result.configNotes) lines.push(`- ${note}`);
    lines.push(``);
  }

  const runSteps = LANG_RUN_INSTRUCTIONS[lang];
  if (runSteps) {
    lines.push(`## How to Run`, ``);
    runSteps.forEach((step, i) =>
      lines.push(`${i + 1}. ${step.replace(/\{filename\}/g, filename)}`)
    );
    lines.push(``);
  }

  lines.push(
    `## Script File`,
    ``,
    `The \`${filename}\` file downloaded alongside this guide contains the full script.`,
    ``,
    `---`,
    `*Generated by [TaskPilot](https://taskpilot-umber.vercel.app)*`,
  );

  return lines.join('\n');
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

const RETRYABLE_STATUSES = new Set([429, 502, 503, 504]);

export async function withRetry<T>(
  fn: () => Promise<T>,
  retries = 3,
  backoffMs = 600,
): Promise<T> {
  let lastErr: unknown;
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      const status = (err as { status?: number })?.status;
      const isTransient =
        !status ||
        RETRYABLE_STATUSES.has(status) ||
        (err instanceof TypeError && err.message.includes('fetch'));
      if (!isTransient || attempt === retries) break;
      const delay = backoffMs * Math.pow(2, attempt);
      console.warn(`[withRetry] attempt ${attempt + 1} failed, retrying in ${delay}ms`, err);
      await new Promise((r) => setTimeout(r, delay));
    }
  }
  throw lastErr;
}

const TRANSIENT_NETWORK_ERROR = /fetch failed|ECONNRESET|ETIMEDOUT|ENOTFOUND|EAI_AGAIN|socket hang up/i;

export function isTransientDbError(message?: string | null): boolean {
  return !!message && TRANSIENT_NETWORK_ERROR.test(message);
}

// supabase-js returns network failures in `error` instead of throwing, so plain
// withRetry never sees them. Re-throw transient ones so they retry; a persistent
// outage (e.g. paused project / dead DNS) surfaces as a thrown TypeError that
// callers map to 503 — never to a business-level "not found".
export async function dbWithRetry<T extends { error: { message?: string } | null }>(
  fn: () => PromiseLike<T>,
  retries = 2,
  backoffMs = 300,
): Promise<T> {
  return withRetry(async () => {
    const res = await fn();
    if (res.error && isTransientDbError(res.error.message)) {
      throw new TypeError(res.error.message);
    }
    return res;
  }, retries, backoffMs);
}
