import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import type { GenerateResult } from '@/app/api/generate/route';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export async function copyToClipboard(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text);
    return;
  } catch {
    // Fallback for browsers where clipboard API is unavailable or denied
  }
  const textarea = document.createElement('textarea');
  textarea.value = text;
  textarea.style.cssText = 'position:fixed;top:0;left:0;opacity:0;pointer-events:none';
  document.body.appendChild(textarea);
  textarea.focus();
  textarea.select();
  try {
    document.execCommand('copy');
  } finally {
    document.body.removeChild(textarea);
  }
}

export function buildDownloadContent(result: GenerateResult): string {
  const lang = result.language ?? '';
  const isLineComment = lang === 'typescript' || lang === 'groovy';
  const c = isLineComment ? '//' : '#';
  if (lang === 'json') return result.script ?? '';

  const sep = `${c} ${'='.repeat(62)}`;
  const lines: string[] = [
    sep,
    `${c} ${result.title ?? 'Generated Script'}`,
    `${c} Generated by TaskPilot — taskpilot-umber.vercel.app`,
    sep,
  ];

  if (result.explanation) {
    lines.push(`${c}`);
    lines.push(`${c} DESCRIPTION:`);
    const words = result.explanation.split(' ');
    let currentLine = `${c}  `;
    for (const word of words) {
      if (currentLine.length + word.length + 1 > 78) {
        lines.push(currentLine.trimEnd());
        currentLine = `${c}  ${word} `;
      } else {
        currentLine += `${word} `;
      }
    }
    if (currentLine.trim() !== c) lines.push(currentLine.trimEnd());
  }

  if (result.configNotes && result.configNotes.length > 0) {
    lines.push(`${c}`);
    lines.push(`${c} BEFORE YOU RUN:`);
    for (const note of result.configNotes) {
      lines.push(`${c}  → ${note}`);
    }
  }

  lines.push(sep);
  lines.push('');
  lines.push(result.script ?? '');
  return lines.join('\n');
}

export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}
