#Requires -Version 5.1

<#
.SYNOPSIS
    Generates a weekly security report of failed login attempts (Event 4625) and
    account lockouts (Event 4740). Exports to CSV and optionally emails the summary.
.EXAMPLE
    .\security-report.ps1
    .\security-report.ps1 -Days 14
#>

[CmdletBinding()]
param(
    [Parameter(HelpMessage = "Number of days to look back (default 7)")]
    [ValidateRange(1, 90)]
    [int]$Days = 7
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Load config ───────────────────────────────────────────────────────────────
$configPath = Join-Path $PSScriptRoot 'config.json'
if (-not (Test-Path $configPath)) { Write-Error "config.json not found at: $configPath"; exit 1 }
$config = Get-Content -Raw $configPath | ConvertFrom-Json

if (-not (Test-Path $config.logPath)) {
    New-Item -ItemType Directory -Path $config.logPath -Force | Out-Null
}
$logFile = Join-Path $config.logPath 'security-report.log'

function Write-Log {
    param([string]$Message, [string]$Level = 'INFO')
    $entry = "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$Level] $Message"
    Add-Content -Path $logFile -Value $entry
    if ($Level -eq 'ERROR') { Write-Error $Message } else { Write-Host $entry }
}

$since     = (Get-Date).AddDays(-$Days)
$reportDir = if ($config.reportPath) { $config.reportPath } else { $config.logPath }
if (-not (Test-Path $reportDir)) { New-Item -ItemType Directory -Path $reportDir -Force | Out-Null }
$datestamp = Get-Date -Format 'yyyyMMdd-HHmmss'

Write-Log "Generating security report for the past $Days day(s) (since $($since.ToString('yyyy-MM-dd')))"

# ── Failed logins — Event ID 4625 ─────────────────────────────────────────────
$failedLogins = [System.Collections.Generic.List[object]]::new()
try {
    $events = Get-WinEvent -FilterHashtable @{ LogName = 'Security'; Id = 4625; StartTime = $since } `
        -ErrorAction SilentlyContinue
    foreach ($ev in $events) {
        $data = @{}
        ([xml]$ev.ToXml()).Event.EventData.Data | Where-Object { $_.Name } |
            ForEach-Object { $data[$_.Name] = $_.'#text' }
        $failedLogins.Add([PSCustomObject]@{
            Time          = $ev.TimeCreated.ToString('yyyy-MM-dd HH:mm:ss')
            TargetAccount = $data['TargetUserName']
            Workstation   = $data['WorkstationName']
            SourceIP      = $data['IpAddress']
        })
    }
    Write-Log "Found $($failedLogins.Count) failed login attempt(s)"
} catch {
    Write-Log "Could not query Security event log for failed logins: $_" 'WARN'
}

# ── Account lockouts — Event ID 4740 ─────────────────────────────────────────
$lockouts = [System.Collections.Generic.List[object]]::new()
try {
    $events = Get-WinEvent -FilterHashtable @{ LogName = 'Security'; Id = 4740; StartTime = $since } `
        -ErrorAction SilentlyContinue
    foreach ($ev in $events) {
        $data = @{}
        ([xml]$ev.ToXml()).Event.EventData.Data | Where-Object { $_.Name } |
            ForEach-Object { $data[$_.Name] = $_.'#text' }
        $lockouts.Add([PSCustomObject]@{
            Time         = $ev.TimeCreated.ToString('yyyy-MM-dd HH:mm:ss')
            LockedAccount = $data['TargetUserName']
            CallerPC      = $data['SubjectDomainName']
        })
    }
    Write-Log "Found $($lockouts.Count) account lockout(s)"
} catch {
    Write-Log "Could not query Security event log for lockouts: $_" 'WARN'
}

# ── Export CSV files ──────────────────────────────────────────────────────────
$attachments = @()

if ($failedLogins.Count -gt 0) {
    $path = Join-Path $reportDir "failed-logins-$datestamp.csv"
    $failedLogins | Export-Csv -Path $path -NoTypeInformation -Encoding UTF8
    $attachments += $path
    Write-Log "Failed logins exported: $path"
}

if ($lockouts.Count -gt 0) {
    $path = Join-Path $reportDir "locked-accounts-$datestamp.csv"
    $lockouts | Export-Csv -Path $path -NoTypeInformation -Encoding UTF8
    $attachments += $path
    Write-Log "Locked accounts exported: $path"
}

# ── Build summary ─────────────────────────────────────────────────────────────
$summary = @"
Security Report — $(Get-Date -Format 'MMMM dd, yyyy')
Reporting period : Last $Days day(s) (since $($since.ToString('yyyy-MM-dd')))

Failed login attempts : $($failedLogins.Count)
Account lockouts      : $($lockouts.Count)

Reports saved to : $reportDir
Generated by     : TaskPilot security-report.ps1
"@

Write-Host $summary

# ── Email summary + attachments ───────────────────────────────────────────────
if ($config.smtpServer -and $config.adminEmail) {
    try {
        $mailParams = @{
            From       = $config.emailFrom
            To         = $config.adminEmail
            Subject    = "Security Report: $($failedLogins.Count) failed logins, $($lockouts.Count) lockouts — $(Get-Date -Format 'MMM dd yyyy')"
            Body       = $summary
            SmtpServer = $config.smtpServer
        }
        if ($attachments.Count -gt 0) { $mailParams['Attachments'] = $attachments }
        Send-MailMessage @mailParams -ErrorAction Stop
        Write-Log "Security report emailed to $($config.adminEmail)"
    } catch {
        Write-Log "Could not send email: $_" 'WARN'
    }
}

Write-Log "=== Security report complete ==="
exit 0
