'use client';

import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { CodeBlock } from '@/components/ui/code-block';
import { TaskComposer } from '@/components/generator/task-composer';
import {
  Webhook, Clock, Play, Mail, FormInput, Database,
  ArrowRight, ArrowLeft, Download, CheckCircle2,
  RefreshCw, Loader2, AlertCircle, Check,
  ThumbsUp, ThumbsDown, Key,
} from 'lucide-react';
import { cn, downloadTextFile } from '@/lib/utils';
import type { WorkflowResult } from '@/app/api/workflow/generate/route';

// ── Types ─────────────────────────────────────────────────────────────────────

type Step = 'trigger' | 'integrations' | 'describe' | 'generating' | 'clarify' | 'result';

interface Trigger { id: string; label: string; desc: string; icon: React.ElementType; }
interface Complexity { id: string; label: string; desc: string; nodes: string; }

// ── Data ──────────────────────────────────────────────────────────────────────

const TRIGGERS: Trigger[] = [
  { id: 'webhook',  label: 'Webhook',  desc: 'Triggered by an incoming HTTP request',     icon: Webhook   },
  { id: 'schedule', label: 'Schedule', desc: 'Runs on a cron interval (e.g. daily 9 am)', icon: Clock     },
  { id: 'manual',   label: 'Manual',   desc: 'Click "Execute" in n8n to run',             icon: Play      },
  { id: 'email',    label: 'Email',    desc: 'Fires when a new email arrives',             icon: Mail      },
  { id: 'form',     label: 'Form',     desc: 'Triggered by a web form submission',         icon: FormInput },
  { id: 'database', label: 'Database', desc: 'Reacts to new or changed database rows',    icon: Database  },
];

const INTEGRATIONS = [
  'Slack', 'Gmail', 'Notion', 'GitHub', 'Stripe', 'PostgreSQL', 'Supabase',
  'HTTP Request', 'Claude AI', 'Google Sheets', 'Airtable', 'Discord',
  'Microsoft Teams', 'Jira', 'Trello', 'HubSpot', 'Salesforce', 'Twilio',
  'Telegram', 'WhatsApp', 'Linear', 'Asana', 'PagerDuty', 'Datadog',
  'AWS S3', 'Dropbox', 'SendGrid', 'Mailchimp', 'RSS Feed', 'Webhook Out',
] as const;

const INTEGRATION_LABELS: Record<string, string> = {
  'Microsoft Teams': 'Teams',
};

const COMPLEXITY_OPTIONS: Complexity[] = [
  { id: 'simple',   label: 'Simple',   desc: 'Linear flow, minimal branching',              nodes: '2–4 nodes'   },
  { id: 'standard', label: 'Standard', desc: 'Conditionals, transformations, error paths',  nodes: '5–10 nodes'  },
  { id: 'complex',  label: 'Complex',  desc: 'Multi-branch, AI-powered, multi-step logic',  nodes: '10–15 nodes' },
];

const TASK_EXAMPLES = [
  'When a new GitHub issue is labeled "urgent", post to Slack #alerts and create a Jira ticket',
  "Every morning at 9am, fetch yesterday's Stripe revenue and post a summary to Slack",
  'When a form is submitted, save to Google Sheets and send a confirmation email via Gmail',
  'When a new row appears in PostgreSQL, analyze it with Claude AI and update a Notion database',
  'Send a daily digest of new GitHub PRs to the team Slack channel',
  'When a Stripe payment fails, send a recovery email via SendGrid and log to Airtable',
  'Every hour, check RSS feed for new articles and post summaries to Discord',
  'When a user signs up, add to Mailchimp, send welcome email, and create a HubSpot contact',
];

const SLOW_GEN_SECONDS = 15;

// ── Helpers ───────────────────────────────────────────────────────────────────

function buildWorkflowGuide(result: WorkflowResult): string {
  const name = result.workflowName ?? 'n8n Workflow';
  const lines: string[] = [
    `# ${name}`,
    ``,
    `> Generated by TaskPilot — https://taskpilot-umber.vercel.app`,
    ``,
  ];

  if (result.description) {
    lines.push(`## Overview`, ``, result.description, ``);
  }

  if (result.nodeCount) {
    lines.push(`**Nodes:** ${result.nodeCount}`, ``);
  }

  if (result.credentials && result.credentials.length > 0) {
    lines.push(`## Credentials Required`, ``, `Set these up in n8n before activating the workflow:`, ``);
    for (const cred of result.credentials) lines.push(`- ${cred}`);
    lines.push(``);
  }

  if (result.importInstructions && result.importInstructions.length > 0) {
    lines.push(`## How to Import`, ``);
    result.importInstructions.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
    lines.push(``);
  }

  lines.push(
    `## Workflow File`,
    ``,
    `The \`workflow.json\` file downloaded alongside this guide is ready to import.`,
    `In n8n: **Workflows → Add Workflow → Import from File** — select \`workflow.json\`.`,
    `Configure the required credentials above, then click **Activate**.`,
    ``,
    `---`,
    `*Generated by [TaskPilot](https://taskpilot-umber.vercel.app)*`,
  );

  return lines.join('\n');
}

// ── Sub-components ────────────────────────────────────────────────────────────

function StepIndicator({ current, total }: { current: number; total: number }) {
  return (
    <div className="mb-8">
      <p className="mb-2 text-xs text-[#6B7280]">
        Step {current + 1} of {total}
      </p>
      <div className="h-px w-full bg-white/8">
        <div
          className="h-px bg-[#3ECF8E] transition-[width] duration-200 ease-out"
          style={{ width: `${((current + 1) / total) * 100}%` }}
        />
      </div>
    </div>
  );
}

function BackLink({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="mb-5 flex items-center gap-1.5 text-[13px] font-medium text-[#A1A1AA] transition-colors duration-150 hover:text-white"
    >
      <ArrowLeft className="h-3.5 w-3.5" /> Back
    </button>
  );
}

// ── Node Diagram Preview ──────────────────────────────────────────────────────

function NodeDiagramPreview({ workflow }: { workflow: Record<string, unknown> }) {
  const nodes = (workflow.nodes as { name?: string; type?: string }[]) ?? [];
  if (nodes.length === 0) return null;
  return (
    <div className="rounded-xl border border-white/8 bg-[#0D0D0D] p-4">
      <p className="mb-3 text-xs font-medium uppercase tracking-wider text-[#6B7280]">Workflow nodes</p>
      <div className="flex flex-wrap items-center gap-y-2">
        {nodes.map((node, i) => (
          <div key={i} className="flex items-center">
            <div className="flex items-center gap-1.5 rounded-md border border-white/8 bg-white/[0.04] px-2 py-1">
              <div className="h-1.5 w-1.5 shrink-0 rounded-full bg-[#3ECF8E]" />
              <span className="font-mono text-xs text-[#E2E8F0]">
                {node.name ?? node.type?.split('.').pop() ?? `Node ${i + 1}`}
              </span>
            </div>
            {i < nodes.length - 1 && <span aria-hidden className="h-px w-3 shrink-0 bg-white/12" />}
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Main Wizard ───────────────────────────────────────────────────────────────

export function WorkflowGenerator() {
  const [step, setStep] = useState<Step>('trigger');
  const [triggerType, setTriggerType] = useState('');
  const [selectedIntegrations, setSelectedIntegrations] = useState<string[]>([]);
  const [complexity, setComplexity] = useState('standard');
  const [task, setTask] = useState('');
  const [clarifyAnswer, setClarifyAnswer] = useState('');
  const [result, setResult] = useState<WorkflowResult | null>(null);
  const [error, setError] = useState('');
  const [elapsed, setElapsed] = useState(0);
  const [slowGen, setSlowGen] = useState(false);
  const abortRef = useRef<AbortController | null>(null);
  const [feedbackRating, setFeedbackRating] = useState<1 | -1 | null>(null);
  const [feedbackComment, setFeedbackComment] = useState('');
  const [feedbackSubmitted, setFeedbackSubmitted] = useState(false);
  const [feedbackSubmitting, setFeedbackSubmitting] = useState(false);

  useEffect(() => {
    if (step !== 'generating') return;
    setElapsed(0);
    setSlowGen(false);
    const tick = setInterval(() => setElapsed((s) => s + 1), 1000);
    const slow = setTimeout(() => setSlowGen(true), SLOW_GEN_SECONDS * 1000);
    return () => {
      clearInterval(tick);
      clearTimeout(slow);
    };
  }, [step]);

  function toggleIntegration(id: string) {
    setSelectedIntegrations((prev) =>
      prev.includes(id)
        ? prev.filter((i) => i !== id)
        : prev.length < 8 ? [...prev, id] : prev
    );
  }

  async function generate(clarificationAnswer?: string, previousQuestion?: string) {
    const controller = new AbortController();
    abortRef.current = controller;
    setStep('generating');
    setError('');
    try {
      const res = await fetch('/api/workflow/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          triggerType,
          integrations: selectedIntegrations,
          complexity,
          taskDescription: task,
          clarificationAnswer,
          previousQuestion,
        }),
        signal: controller.signal,
      });
      const data: WorkflowResult & { error?: string } = await res.json();

      if (!res.ok) {
        setError(data.error ?? 'Generation failed. Please try again.');
        setStep('describe');
        return;
      }

      if (data.needsClarification && data.question) {
        setResult(data);
        setStep('clarify');
      } else {
        setResult(data);
        setStep('result');
      }
    } catch (err) {
      if (err instanceof DOMException && err.name === 'AbortError') return;
      setError('Network error. Check your connection and try again.');
      setStep('describe');
    }
  }

  function stopGeneration() {
    abortRef.current?.abort();
    setStep('describe');
  }

  async function submitFeedback(rating: 1 | -1) {
    if (feedbackSubmitted || feedbackSubmitting) return;
    setFeedbackRating(rating);
    setFeedbackSubmitting(true);
    try {
      await fetch('/api/workflow/feedback', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          triggerType,
          integrations: selectedIntegrations,
          complexity,
          rating,
          comment: feedbackComment.trim() || undefined,
        }),
      });
    } catch { /* non-critical */ }
    finally {
      setFeedbackSubmitted(true);
      setFeedbackSubmitting(false);
    }
  }

  function reset() {
    setStep('trigger');
    setTriggerType('');
    setSelectedIntegrations([]);
    setComplexity('standard');
    setTask('');
    setClarifyAnswer('');
    setResult(null);
    setError('');
    setFeedbackRating(null);
    setFeedbackComment('');
    setFeedbackSubmitted(false);
    setFeedbackSubmitting(false);
  }

  const workflowJson = result?.workflow ? JSON.stringify(result.workflow, null, 2) : null;

  // ── Render ─────────────────────────────────────────────────────────────────

  return (
    <div className="w-full max-w-2xl mx-auto">

      {/* ── Step: Trigger ──────────────────────────────────────────────────── */}
      {step === 'trigger' && (
        <div className="animate-slide-up">
          <StepIndicator current={0} total={3} />
          <h2 className="mb-1 text-xl font-semibold tracking-tight text-[#F9FAFB]">How does the workflow start?</h2>
          <p className="mb-6 text-sm text-[#A1A1AA]">Choose the event that kicks off your automation.</p>
          <div className="grid gap-3 sm:grid-cols-2">
            {TRIGGERS.map((t) => {
              const Icon = t.icon;
              const selected = triggerType === t.id;
              return (
                <button
                  type="button"
                  key={t.id}
                  onClick={() => { setTriggerType(t.id); setStep('integrations'); }}
                  aria-pressed={selected}
                  className={cn(
                    'card-lift relative w-full rounded-xl border bg-[#0D0D0D] p-4 text-left',
                    selected ? 'border-[rgba(62,207,142,0.4)]' : 'border-white/8'
                  )}
                >
                  {selected && <Check className="absolute right-3 top-3 h-3.5 w-3.5 text-[#3ECF8E]" />}
                  <Icon className="mb-3 h-4 w-4 text-[#6B7280]" />
                  <div className="mb-1 text-sm font-medium text-[#F9FAFB]">{t.label}</div>
                  <div className="text-xs leading-relaxed text-[#A1A1AA]">{t.desc}</div>
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Step: Integrations ─────────────────────────────────────────────── */}
      {step === 'integrations' && (
        <div className="animate-slide-up">
          <StepIndicator current={1} total={3} />
          <BackLink onClick={() => setStep('trigger')} />
          <h2 className="mb-1 text-xl font-semibold tracking-tight text-[#F9FAFB]">Which apps do you need?</h2>
          <p className="mb-1 text-sm text-[#A1A1AA]">Select up to 8 integrations. Skip if not sure.</p>
          <p className={cn('mb-4 text-xs text-[#6B7280]', selectedIntegrations.length === 0 && 'invisible')}>
            {selectedIntegrations.length}/8 selected
          </p>

          <div className="mb-6 flex flex-wrap gap-2">
            {INTEGRATIONS.map((id) => {
              const active = selectedIntegrations.includes(id);
              return (
                <button
                  type="button"
                  key={id}
                  onClick={() => toggleIntegration(id)}
                  className={cn(
                    'rounded-lg border px-3 py-1.5 text-[13px] font-medium transition-colors duration-150',
                    active
                      ? 'border-[rgba(62,207,142,0.4)] text-[#3ECF8E]'
                      : 'border-white/8 text-[#A1A1AA] hover:border-white/25 hover:text-white',
                    !active && selectedIntegrations.length >= 8 && 'pointer-events-none opacity-40'
                  )}
                >
                  {active && <Check className="mr-1 inline h-3.5 w-3.5" />}
                  {INTEGRATION_LABELS[id] ?? id}
                </button>
              );
            })}
          </div>

          {/* Complexity */}
          <div className="mb-6">
            <p className="mb-3 text-xs font-medium uppercase tracking-wider text-[#6B7280]">Workflow complexity</p>
            <div className="grid grid-cols-3 gap-2">
              {COMPLEXITY_OPTIONS.map((c) => {
                const selected = complexity === c.id;
                return (
                  <button
                    type="button"
                    key={c.id}
                    onClick={() => setComplexity(c.id)}
                    aria-pressed={selected}
                    className={cn(
                      'rounded-xl border bg-[#0D0D0D] p-3 text-left transition-colors duration-150',
                      selected
                        ? 'border-[rgba(62,207,142,0.4)]'
                        : 'border-white/8 hover:border-white/25'
                    )}
                  >
                    <div className={cn('mb-0.5 text-sm font-medium', selected ? 'text-[#F9FAFB]' : 'text-[#A1A1AA]')}>
                      {c.label}
                    </div>
                    <div className="text-xs text-[#6B7280]">{c.nodes}</div>
                  </button>
                );
              })}
            </div>
          </div>

          <Button onClick={() => setStep('describe')} size="lg" className="w-full">
            Continue <ArrowRight className="h-4 w-4" />
          </Button>
        </div>
      )}

      {/* ── Step: Describe ─────────────────────────────────────────────────── */}
      {step === 'describe' && (
        <div className="animate-slide-up">
          <StepIndicator current={2} total={3} />
          <BackLink onClick={() => setStep('integrations')} />
          <h2 className="mb-1 text-xl font-semibold tracking-tight text-[#F9FAFB]">Describe your automation</h2>
          <p className="mb-6 text-sm text-[#A1A1AA]">Plain English. Include the trigger event, what to do, and where to send results.</p>

          <div className="mb-4">
            <TaskComposer
              value={task}
              onChange={setTask}
              onSubmit={() => { if (task.trim().length >= 10) generate(); }}
              disabled={task.trim().length < 10}
              maxLength={2000}
              placeholder="e.g. When a new GitHub issue is labeled 'urgent', post a Slack message to #alerts and create a Jira ticket with the issue title and URL."
              submitLabel="Generate"
              error={error || undefined}
              autoFocus
            />
          </div>

          <div>
            <p className="mb-2 text-xs font-medium uppercase tracking-wider text-[#6B7280]">Examples</p>
            <div className="flex flex-wrap gap-2">
              {TASK_EXAMPLES.map((ex) => (
                <button
                  key={ex}
                  onClick={() => setTask(ex)}
                  className="rounded-lg border border-white/8 px-2.5 py-1 text-left text-xs text-[#A1A1AA] transition-colors duration-150 hover:border-white/25 hover:text-[#F9FAFB]"
                >
                  {ex.length > 60 ? ex.slice(0, 60) + '…' : ex}
                </button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Step: Generating ───────────────────────────────────────────────── */}
      {step === 'generating' && (
        <div className="animate-fade-in py-8">
          <div className="mb-6 rounded-xl border border-white/8 bg-[#0D0D0D] p-4">
            <p className="mb-1.5 text-xs font-medium uppercase tracking-wider text-[#6B7280]">Automation</p>
            <p className="text-sm leading-relaxed text-[#A1A1AA]">{task}</p>
          </div>
          <div className="flex items-center justify-between" aria-live="polite">
            <p className="stream-caret text-sm text-[#F9FAFB]">Building your n8n workflow</p>
            <div className="flex items-center gap-4">
              <span className="text-xs tabular-nums text-[#6B7280]">{elapsed}s</span>
              <button
                type="button"
                onClick={stopGeneration}
                className="text-[13px] font-medium text-[#A1A1AA] transition-colors duration-150 hover:text-white"
              >
                Stop
              </button>
            </div>
          </div>
          {slowGen && (
            <p className="mt-3 text-xs text-[#6B7280]">Complex workflows can take up to 30 seconds.</p>
          )}
        </div>
      )}

      {/* ── Step: Clarify ──────────────────────────────────────────────────── */}
      {step === 'clarify' && result?.question && (
        <div className="animate-slide-up">
          <StepIndicator current={2} total={3} />
          <div className="mb-6 rounded-xl border border-white/8 bg-[#0D0D0D] p-4">
            <p className="mb-1.5 text-xs font-medium uppercase tracking-wider text-[#6B7280]">One question before generating</p>
            <p className="text-sm leading-relaxed text-[#F9FAFB]">{result.question}</p>
          </div>
          <div className="space-y-3">
            <Input
              value={clarifyAnswer}
              onChange={(e) => setClarifyAnswer(e.target.value)}
              placeholder="Your answer"
              autoFocus
              onKeyDown={(e) => {
                if (e.key === 'Enter' && clarifyAnswer.trim()) generate(clarifyAnswer.trim(), result.question!);
              }}
            />
            <Button
              onClick={() => generate(clarifyAnswer.trim(), result.question!)}
              disabled={!clarifyAnswer.trim()}
              size="lg"
              className="w-full"
            >
              Answer and generate
            </Button>
          </div>
        </div>
      )}

      {/* ── Step: Result ───────────────────────────────────────────────────── */}
      {step === 'result' && result && (
        <div className="animate-slide-up space-y-5">

          {/* Header */}
          <div>
            <div className="mb-1 flex items-center gap-2">
              {result.workflow
                ? <CheckCircle2 className="h-4 w-4 shrink-0 text-[#3ECF8E]" />
                : <AlertCircle className="h-4 w-4 shrink-0 text-[#A1A1AA]" />}
              <h2 className="text-xl font-semibold tracking-tight text-[#F9FAFB]">
                {result.workflow ? (result.workflowName ?? 'Your workflow is ready') : 'Generation incomplete'}
              </h2>
            </div>
            {result.workflow && result.nodeCount ? (
              <p className="pl-6 text-sm leading-relaxed text-[#A1A1AA]">
                {result.nodeCount} nodes{result.description ? ` · ${result.description}` : ''}
              </p>
            ) : null}
            {!result.workflow && (
              <p className="mt-1 pl-6 text-sm leading-relaxed text-[#A1A1AA]">
                The generator could not produce a complete workflow. Add more detail: name the trigger, the apps involved, and what each step should do.
              </p>
            )}
          </div>

          {/* Node diagram */}
          {result.workflow && <NodeDiagramPreview workflow={result.workflow} />}

          {/* JSON output */}
          {workflowJson && (
            <CodeBlock
              code={workflowJson}
              language="json"
              filename="workflow.json"
              languageLabel="n8n JSON"
              maxHeight={400}
            />
          )}

          {/* Actions */}
          {result.workflow ? (
            <div className="flex flex-col gap-3 sm:flex-row">
              <Button
                onClick={() => {
                  if (!workflowJson) return;
                  const slug = result.workflowName?.toLowerCase().replace(/\s+/g, '-') ?? 'workflow';
                  downloadTextFile(workflowJson, `${slug}.json`);
                  setTimeout(() => downloadTextFile(buildWorkflowGuide(result), `${slug}-guide.md`), 150);
                }}
                variant="outline"
                className="gap-2"
              >
                <Download className="h-4 w-4" />
                Download .json + guide
              </Button>
              <Button onClick={reset} variant="ghost" className="gap-2">
                <RefreshCw className="h-4 w-4" />
                New workflow
              </Button>
            </div>
          ) : (
            <Button onClick={reset} variant="outline" className="gap-2">
              <RefreshCw className="h-4 w-4" />
              Try again
            </Button>
          )}

          {/* Credentials */}
          {result.credentials && result.credentials.length > 0 && (
            <div className="rounded-xl border border-white/8 bg-white/[0.03] p-4">
              <p className="mb-2.5 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wider text-[#A1A1AA]">
                <Key className="h-3.5 w-3.5" /> Credentials required
              </p>
              <ul className="space-y-1.5">
                {result.credentials.map((cred, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs leading-relaxed text-[#A1A1AA]">
                    <span className="mt-0.5 shrink-0 text-[#6B7280]">•</span>
                    {cred}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Import instructions */}
          {result.importInstructions && result.importInstructions.length > 0 && (
            <div className="rounded-xl border border-white/8 bg-white/[0.03] p-4">
              <p className="mb-2.5 text-xs font-medium uppercase tracking-wider text-[#A1A1AA]">How to import</p>
              <ol className="space-y-1.5">
                {result.importInstructions.map((step, i) => (
                  <li key={i} className="flex items-start gap-2.5 text-xs leading-relaxed text-[#A1A1AA]">
                    <span className="mt-0.5 w-3.5 shrink-0 text-xs text-[#6B7280]">{i + 1}.</span>
                    {step}
                  </li>
                ))}
              </ol>
            </div>
          )}

          {/* Feedback */}
          {result.workflow && (
            feedbackSubmitted ? (
              <p className="text-xs text-[#A1A1AA]">Thanks. This improves future workflows.</p>
            ) : feedbackRating === -1 ? (
              <div className="space-y-3">
                <Textarea
                  value={feedbackComment}
                  onChange={(e) => setFeedbackComment(e.target.value)}
                  placeholder="What went wrong? Optional, helps improve the generator."
                  rows={2}
                  maxLength={500}
                  className="resize-none text-sm"
                  autoFocus
                />
                <div className="flex gap-2">
                  <Button size="sm" onClick={() => submitFeedback(-1)} disabled={feedbackSubmitting} className="gap-1.5">
                    {feedbackSubmitting && <Loader2 className="h-3.5 w-3.5 animate-spin" />}
                    Submit feedback
                  </Button>
                  <Button variant="ghost" size="sm" onClick={() => setFeedbackRating(null)} disabled={feedbackSubmitting}>
                    Cancel
                  </Button>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-3">
                <p className="text-xs text-[#A1A1AA]">Did this workflow work?</p>
                <button
                  type="button"
                  aria-label="Yes, it worked"
                  onClick={() => submitFeedback(1)}
                  disabled={feedbackSubmitting}
                  className="rounded-lg border border-white/8 p-1.5 text-[#A1A1AA] transition-colors duration-150 hover:border-white/25 hover:text-white"
                >
                  <ThumbsUp className="h-3.5 w-3.5" />
                </button>
                <button
                  type="button"
                  aria-label="No, it needs work"
                  onClick={() => setFeedbackRating(-1)}
                  disabled={feedbackSubmitting}
                  className="rounded-lg border border-white/8 p-1.5 text-[#A1A1AA] transition-colors duration-150 hover:border-white/25 hover:text-white"
                >
                  <ThumbsDown className="h-3.5 w-3.5" />
                </button>
              </div>
            )
          )}

          {/* Upsell */}
          {result.workflow && (
            <p className="text-[13px] text-[#A1A1AA]">
              Need production-ready PowerShell scripts too?{' '}
              <a href="/checkout" className="font-medium text-[#3ECF8E] transition-colors duration-150 hover:text-[#5FDCA5]">
                The Starter Kit has 9 for $19
              </a>
              .
            </p>
          )}
        </div>
      )}
    </div>
  );
}
