'use strict';

// Scheduled production health check, run from GitHub Actions runners.
// Claude cloud routines cannot probe the live site (the sandbox egress proxy
// 403-blocks non-allowlisted domains like *.vercel.app), so the probes live
// here and routines read the results via the GitHub API instead.
//
// Checks: homepage 200 + title, /generate 200, security headers, and a live round trip
// through /api/assistant. The AI probe exists because on Sep 20 2026 the Anthropic credit
// balance ran out and every page here stayed green throughout: a page returning 200 says
// nothing about whether the model behind it still answers. Probe the effect, not the page.
// On failure: deduped issue (label: site-health) + non-zero exit so the
// scheduled-run failure email fires. On recovery: auto-closes open issues.

const GH_TOKEN = process.env.GH_TOKEN;
const REPO = process.env.REPO;
const SITE = process.env.SITE || 'https://taskpilot-umber.vercel.app';
const LABEL = 'site-health';
const SLOW_MS = 3000;
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const REQUIRED_HEADERS = ['strict-transport-security', 'x-frame-options', 'x-content-type-options'];

if (!GH_TOKEN) { console.error('Missing GH_TOKEN'); process.exit(1); }
if (!REPO) { console.error('Missing REPO'); process.exit(1); }

const API = `https://api.github.com/repos/${REPO}`;
const HEADERS = {
  Authorization: `Bearer ${GH_TOKEN}`,
  Accept: 'application/vnd.github+json',
  'X-GitHub-Api-Version': '2022-11-28',
};

async function gh(path, options = {}) {
  return fetch(`${API}${path}`, {
    ...options,
    headers: { ...HEADERS, ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...options.headers },
  });
}

async function probe(url, { readBody = false } = {}) {
  const started = Date.now();
  try {
    const res = await fetch(url, {
      headers: { 'User-Agent': UA },
      redirect: 'follow',
      signal: AbortSignal.timeout(15000),
    });
    const body = readBody && res.status === 200 ? await res.text() : '';
    return { status: res.status, ms: Date.now() - started, headers: res.headers, body };
  } catch (err) {
    return { status: 0, ms: Date.now() - started, error: err.message, body: '' };
  }
}

// One retry after 30s smooths over cold starts and transient edge blips.
async function probeWithRetry(url, opts) {
  const first = await probe(url, opts);
  if (first.status === 200 && first.ms <= SLOW_MS) return first;
  await new Promise(r => setTimeout(r, 30000));
  const second = await probe(url, opts);
  return second.status === 200 ? second : { ...second, firstAttempt: first };
}

function classify(result) {
  if (result.status === 200) return 'ok';
  // Vercel bot mitigation is known to 403 datacenter IPs hitting this app;
  // that is inconclusive (monitor blocked), not an outage for real users.
  if (result.status === 403) return 'inconclusive';
  return 'fail';
}

async function getOpenIssues() {
  const res = await gh(`/issues?labels=${LABEL}&state=open`);
  if (!res.ok) return [];
  const issues = await res.json();
  return Array.isArray(issues) ? issues : [];
}

async function ensureLabel() {
  const res = await gh('/labels', {
    method: 'POST',
    body: JSON.stringify({ name: LABEL, color: 'b60205', description: 'Automated production health check findings' }),
  });
  if (!res.ok && res.status !== 422) console.warn(`Label create returned ${res.status}`);
}

async function report(lines, severity) {
  const today = new Date().toISOString().slice(0, 10);
  const body = `## Site Health — ${today} (${severity})\n\nSite: ${SITE}\n\n${lines.map(l => `- ${l}`).join('\n')}\n\n---\n*Generated by [Site Health](../../actions/workflows/site-health.yml), which probes production from GitHub runners every 6 hours. A 403 means the probe was edge-blocked (bot mitigation), not that the site is down for real users.*`;
  const open = await getOpenIssues();
  if (open.length > 0) {
    const res = await gh(`/issues/${open[0].number}/comments`, { method: 'POST', body: JSON.stringify({ body }) });
    if (!res.ok) throw new Error(`Comment failed: ${res.status} ${await res.text()}`);
    console.log(`Appended findings to existing issue #${open[0].number}`);
    return;
  }
  await ensureLabel();
  const res = await gh('/issues', {
    method: 'POST',
    body: JSON.stringify({ title: `Site health: ${severity} [${today}]`, body, labels: [LABEL] }),
  });
  if (!res.ok) throw new Error(`Issue create failed: ${res.status} ${await res.text()}`);
  console.log(`Issue created: ${(await res.json()).html_url}`);
}

async function closeOpenIssues() {
  for (const issue of await getOpenIssues()) {
    await gh(`/issues/${issue.number}/comments`, {
      method: 'POST',
      body: JSON.stringify({ body: `All checks passing again as of ${new Date().toISOString()} — closing.` }),
    });
    await gh(`/issues/${issue.number}`, {
      method: 'PATCH',
      body: JSON.stringify({ state: 'closed', state_reason: 'completed' }),
    });
    console.log(`Site healthy — closed issue #${issue.number}`);
  }
}

// Functional probe of the assistant. A 200 from /generate proves the page renders, not that
// the model behind it responds. The route streams text/plain on success and JSON on failure,
// so this reads the body and requires actual content back.
async function probeAssistant() {
  const started = Date.now();
  try {
    const res = await fetch(`${SITE}/api/assistant`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'User-Agent': UA },
      body: JSON.stringify({ messages: [{ role: 'user', content: 'ping' }] }),
      signal: AbortSignal.timeout(45000),
    });
    const text = await res.text();
    return { status: res.status, ms: Date.now() - started, text };
  } catch (err) {
    return { status: 0, ms: Date.now() - started, error: err.message };
  }
}

async function main() {
  const failures = [];
  const warnings = [];

  const home = await probeWithRetry(SITE, { readBody: true });
  console.log(`Homepage: HTTP ${home.status} in ${home.ms}ms`);
  const homeState = classify(home);
  if (homeState === 'fail') {
    failures.push(`**Homepage DOWN:** HTTP ${home.status || `0 (${home.error})`} after retry.`);
  } else if (homeState === 'inconclusive') {
    warnings.push(`**Homepage inconclusive:** HTTP 403 after retry — probe likely edge-blocked, verify manually.`);
  } else {
    if (home.ms > SLOW_MS) {
      warnings.push(`**Homepage slow:** ${home.ms}ms (threshold ${SLOW_MS}ms), even after retry.`);
    }
    if (!/<title[^>]*>[^<]*TaskPilot/i.test(home.body)) {
      failures.push('**Title check failed:** homepage returned 200 but "TaskPilot" is missing from the <title> tag — wrong content is being served.');
    }
    const missing = REQUIRED_HEADERS.filter(h => !home.headers.get(h));
    if (missing.length > 0) {
      failures.push(`**Security headers missing:** ${missing.join(', ')} — deploy/config regression.`);
    } else {
      console.log('Security headers: all present');
    }
  }

  const gen = await probeWithRetry(`${SITE}/generate`);
  console.log(`/generate: HTTP ${gen.status} in ${gen.ms}ms`);
  const genState = classify(gen);
  if (genState === 'fail') {
    failures.push(`**/generate DOWN:** HTTP ${gen.status || `0 (${gen.error})`} after retry.`);
  } else if (genState === 'inconclusive') {
    warnings.push(`**/generate inconclusive:** HTTP 403 after retry — probe likely edge-blocked.`);
  }

  const ai = await probeAssistant();
  console.log(`AI /api/assistant: HTTP ${ai.status} in ${ai.ms}ms`);
  if (ai.status === 200 && (ai.text || '').trim().length > 0) {
    console.log('Pilot AI: answering');
  } else if (ai.status === 403) {
    warnings.push('**Pilot inconclusive:** /api/assistant returned 403 — probe likely edge-blocked, verify manually.');
  } else if (ai.status === 429) {
    warnings.push('**Pilot rate limited:** /api/assistant returned 429 — the probe hit the per-IP ceiling, not an outage.');
  } else if (ai.status === 200) {
    failures.push('**Pilot returning empty answers:** /api/assistant returned 200 with an empty body.');
  } else {
    // 502 is what the route returns for any upstream failure, exhausted API credits included.
    failures.push(`**Pilot DOWN:** /api/assistant returned ${ai.status || `0 (${ai.error})`}. Check the Anthropic credit balance and ANTHROPIC_API_KEY in Vercel.`);
  }

  if (failures.length === 0 && warnings.length === 0) {
    await closeOpenIssues();
    console.log('All checks passed.');
    return;
  }

  const severity = failures.length > 0 ? 'FAILING' : 'warning';
  await report([...failures, ...warnings], severity);
  if (failures.length > 0) process.exit(1);
}

main().catch(err => { console.error(err); process.exit(1); });
